### ISSUE TITLE
This is a tracking bug, both for HTML and for the wider web ecosystem, to see if we can minimize the number of places that use the entry global/settings object/realm. Originally this was https://www.w3.org/Bugs/Public/show_bug.cgi?id=27203.implementation-defined Referenced in: 2.3. Terminology (2) 3.2. Avoid limits on algorithm inputs (2) (3) Possible linking syntaxes:  [=implementation-defined=]  [=/implementationimplementation-defined Referenced in: 2.3. Terminology (2) 3.2. Avoid limits on algorithm inputs (2) (3) Possible linking syntaxes:  [=implementation-defined=]  [=/implementation

### ISSUE THREAD

**Issue by Olol123579** [cypht-org/cypht#1332]
This is a tracking bug, both for HTML and for the wider web ecosystem, to see if we can minimize the number of places that use the entry global/settings object/realm. Originally this was https://www.w3.org/Bugs/Public/show_bug.cgi?id=27203.

Here is our HTML checklist:
- [x] [XMLDocument's load() URL parsing](https://html.spec.whatwg.org/#loading-xml-documents:entry-settings-object) [#1478]
- [ ] [Setting the request client for downloading a hyperlink](https://html.spec.whatwg.org/#downloading-resources:entry-settings-object)
- [x] [Origin-clean checking for canvas image sources](https://html.spec.whatwg.org/#image-sources-for-2d-rendering-contexts:entry-settings-object) [#6656]
- [x] [Origin-clean setting for canvas font drawing](https://html.spec.whatwg.org/#drawing-text-to-the-bitmap:entry-settings-object) [#1549]
- [x] [frameElement same-origin checks](https://html.spec.whatwg.org/#navigating-nested-browsing-contexts-in-the-dom:entry-settings-object) [#1541]
- [ ] [window.open()](https://html.spec.whatwg.org/#apis-for-creating-and-navigating-browsing-contexts-by-name:entry-settings-object)
  - https://url-parsing-entry-iaqyojravh.now.sh/entry/entry.html shows this uses entry in all browsers; unlikely to be able to change this
- [x] [URL parsing and origin-checking in pushState/replaceState](https://html.spec.whatwg.org/#the-history-interface:entry-settings-object) [#1479, #1541]
- [ ] [Origin-checking in the Location object](https://html.spec.whatwg.org/#the-location-interface:entry-settings-object)
- [ ] [Origin-checking in document.open()](https://html.spec.whatwg.org/#opening-the-input-stream:entry-global-object)
- [x] [URL parsing and origin-checking for registerProtocol/ContentHandler](https://html.spec.whatwg.org/#custom-handlers:entry-settings-object) [#1541]
- [x] [Origin-clean setting for ImageBitmaps](https://html.spec.whatwg.org/#images:entry-settings-object) [#6656]
- [x] [Establishing a WebSocket connection](https://html.spec.whatwg.org/#the-websocket-interface:entry-settings-object) [#6655]
- [x] [Origin-checking in postMessage](https://html.spec.whatwg.org/#posting-messages:entry-settings-object) [#1542, #1573]
- [x] [URL parsing in the Worker constructor](https://html.spec.whatwg.org/#posting-messages:entry-settings-object) (see also SharedWorker)  [#1472]
- [ ] Error reporting plans to start using entry!? https://github.com/whatwg/html/issues/958

Fetch:
- [x] [Request constructor URL window association and URL parsing](https://fetch.spec.whatwg.org/#dom-request) [https://github.com/whatwg/fetch/issues/367]
- [x] [Response constructor HTTP state propagation](https://fetch.spec.whatwg.org/#dom-response) [https://github.com/whatwg/fetch/issues/367]
- [x] [Response.redirect URL parsing](https://fetch.spec.whatwg.org/#dom-response-redirect) [https://github.com/whatwg/fetch/issues/367]

Service Worker:
- [x] [register URL parsing](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-container-register-method) [https://github.com/w3c/ServiceWorker/pull/963]
- [x] [getRegistration URL parsing](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-container-getregistration-method) [https://github.com/w3c/ServiceWorker/pull/963]
- [x] [navigate URL parsing](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#client-navigate-method) [https://github.com/w3c/ServiceWorker/pull/950]
- [x] [openWindow URL parsing](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#clients-openwindow-method) [https://github.com/w3c/ServiceWorker/pull/950]
- [x] [registerForeignFetch URL parsing](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#dom-installevent-registerforeignfetch) [https://github.com/w3c/ServiceWorker/pull/950]
- [x] [Start Register URL parsing](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#start-register-algorithm) [https://github.com/w3c/ServiceWorker/pull/963]

XHR (https://github.com/whatwg/xhr/issues/98):

- [x] [xhr.timeout attribute Window check](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-timeout)
- [x] [xhr.responseType Window check](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-responsetype)
- [x] [xhr.open() Window check](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-open)

Notifications (https://github.com/whatwg/notifications/issues/86):

- [x] [a newly-created notification's origin and API base URL](https://notifications.spec.whatwg.org/#create-a-notification)
- [x] [permission getter](https://notifications.spec.whatwg.org/#dom-notification-permission)
- [x] [requestPermission origin permission association](https://notifications.spec.whatwg.org/#dom-notification-requestpermission)
- [x] [getNotifications origin permission association](https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-getnotifications)

If you have other specs that use the entry concept, comment here and I will update the OP.

_Ursprünglich gepostet von @domenic in https://github.com/whatwg/html/issues/1431_
